### PR TITLE
avoid referencing entity classes while patching

### LINKED ISSUE #3: bedpatch v2.1 (1.12.2) preventing sponge from loading
Early reference error. Early mod classloading of NMS classes is causing sponge mixin to fail. 

Logs:

https://gist.github.com/colinrgodsey/aa77126abbc49f46157e798700f3bea2

### PR DESCRIPTION
**Pull request by colinrgodsey**
.

### CODE REVIEW

**Comment by colinrgodsey** [comment]
and to reiterate- it looked like you were causing the classloader to load (and therefor solidify) the EntityPlayer class before everything had a chance to patch it. This way the new class I made (with the EntityPlayer and other NMS references) will be lazy loaded naturally as a static class way after the patching phase, the first time that method is run.

**Comment by Mordenkainen** [comment]
So the issue was simply that I had a reference to EntityPlayer in the same class as the actual patch code?

Like WTF?

**Comment by colinrgodsey** [comment]
would appear so 🤷‍♂️

**Comment by Mordenkainen** [comment]
Well... Thanks!

I'll see about getting this posted shortly.

**Pull request merged**
